[package]
name = "wyndex-tests"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
cw20 = { workspace = true }
cw20-base = {workspace = true}
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
cw-multi-test = { workspace = true }
wyndex = { workspace = true }
wyndex-factory = { workspace = true }
wyndex-multi-hop = { workspace = true }
wyndex-pair-lsd = { workspace = true }
wyndex-pair = { workspace = true }
wyndex-stake = { workspace = true }
utils = { workspace = true }